spring:
  application:
    name: projetoBase

  datasource:
    url: jdbc:mysql://localhost:3306/users?createDatabaseIfNotExist=true
    # ajuste aqui as credenciais do seu mysql.
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: c2VjcmV0S2V5UGFyYU9Qcm9qZXRvQmFzZVNwcmluZ1NlY3VyaXR5SmF2YQ==
  expiration-ms: 86400000

